language: cpp

os: linux

dist: xenial

compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get -y install qt5-default=5.5.1+dfsg-16ubuntu7.6
    
script:
  - qmake Qontainer.pro
  - make
